export const FEE_LIFETIME = 30 * 1000; // ms
export const UPDATE_INTERVAL = 60 * 1000; // 1 minute
export const AUTHENTICATION_LOST_DELAY = 3000;
export const SEND_MODAL_WINDOW_LIFETIME = 3 * 60 * 1000; // 3 minutes
export const CLIENT_IP_HASH_LIFETIME = 300 * 1000; // ms
export const COINS_TO_FIAT_RATES_LIFETIME = 180 * 1000; // ms
export const USD_FIAT_RATES_LIFETIME = 2 * 60 * 60 * 1000; // ms, 2h
export const IS_TESTING = false;
export const API_URL = "";
export const TABLE_ROWS_COUNT = 10;
export const SUPPORT_EMAIL = "support@rabbit.io";
export const SUPPORT_PGP_KEY_LINK = "https://rabbit.io/key.pub";
export const WORK_ON_BLOCKCHAIN_NETWORKS_OF_TYPE = "main"; // all possible options: "main", "test"
export const ETH_PR_K = "RR0IlSeHstH7PWdMsh8y9zrFWQ_jbmdc";
export const ETH_PR_ALC_GOERLI_K = ""; // We don't use testnet for prod
export const ETH_PR_K_ETHSCAN = "W73GZKDSGPP851QYA3XQPVITUJ6A48UCEI";
export const MAX_ATTEMPTS_TO_RETRIEVE_TRANSACTIONS_DATA = 80;
export const LANDING_PATH = "/";
export const RAMP_NETWORK_API_KEY = "kghgdufkvmz8mxva8a3wkb2srs8ykx58c2v2vwfx";
export const RAMP_WEBHOOK_STATUS_URL = "https://rabbit.io/api/v1/webhooks/ramp";
export const RAMP_WIDGET_STAGING_URL = "";
export const PUBLIC_LOGO_LINK = "https://rabbit.io/logo.svg";
export const LOG_LEVEL = "trace"; // of "trace", "debug"
export const TRONGR_PR_K = "76cb8227-1c29-4d0d-bb3b-bff241979160";
export const GETBL_PR_K = "ce6dc4e1-0f94-46e8-ba29-8e7aeeedd140";
