export const FEE_LIFETIME = 30 * 1000; // ms
export const UPDATE_INTERVAL = 60 * 1000; // 1 minute
export const AUTHENTICATION_LOST_DELAY = 3000;
export const SEND_MODAL_WINDOW_LIFETIME = 3 * 60 * 1000; // 3 minutes
export const FEE_RATES_SERVICE_ENDPOINT = "https://lightrium.io/feerates";
export const CHANGE_ADDRESS_UPDATE_INTERVAL_SECONDS = 300;
export const CLIENT_IP_HASH_LIFETIME = 300 * 1000; // ms
export const BTC_FIAT_RATES_LIFETIME = 180 * 1000; // ms
export const USD_FIAT_RATES_LIFETIME = 2 * 60 * 60 * 1000; // ms, 2h
export const IS_TESTING = false;
export const API_URL = "";
export const TABLE_ROWS_COUNT = 10;
export const SUPPORT_EMAIL = "support@rabbit.io";
export const SUPPORT_PGP_KEY_LINK = "https://rabbit.io/key.pub";
export const BTC_NETWORK_KEY = "mainnet";
export const SUPPORTED_NETWORKS_KEYS = ["mainnet"];
export const MAX_COUNT_OF_ATTEMPTS_FOR_DATA_RETRIEVAL = 50;
export const MAX_ATTEMPTS_TO_RETRIEVE_TRANSACTIONS_DATA = 80;
export const LANDING_PATH = "/";
export const RAMP_NETWORK_API_KEY = "kghgdufkvmz8mxva8a3wkb2srs8ykx58c2v2vwfx";
export const RAMP_WEBHOOK_STATUS_URL = "https://rabbit.io/api/v1/webhooks/ramp";
export const RAMP_WIDGET_STAGING_URL = "";
export const PUBLIC_LOGO_LINK = "https://rabbit.io/logo.svg";
