export const FEE_LIFETIME = 30 * 1000; // ms
export const UPDATE_INTERVAL = 60 * 1000; // 1 minute
export const AUTHENTICATION_LOST_DELAY = 3000; // 3 min
export const SEND_MODAL_WINDOW_LIFETIME = 3 * 60 * 1000; // 3 minutes
export const FEE_RATES_SERVICE_ENDPOINT = "https://lightrium.io/feerates";
export const CHANGE_ADDRESS_UPDATE_INTERVAL_SECONDS = 300;
export const CLIENT_IP_HASH_LIFETIME = 30 * 1000; // ms
export const COINS_TO_FIAT_RATES_LIFETIME = 30 * 1000; // ms
export const USD_FIAT_RATES_LIFETIME = 2 * 60 * 60 * 1000; // ms
export const IS_TESTING = true;
export const API_URL = "";
export const TABLE_ROWS_COUNT = 10;
export const SUPPORT_EMAIL = "support@rabbit.io";
export const SUPPORT_PGP_KEY_LINK = "https://rabbit.io/key.pub";
export const WORK_ON_BLOCKCHAIN_NETWORKS_OF_TYPE = "main"; // all possible options: "main", "test"
export const ETH_PR_K = "z3Cy0cTOuGtVmT0FI2NVG6P7hyO_2Qpo"; // Note: depends on the network, see alchemy docs
export const ETH_PR_K_ETHSCAN = "6SVG5JCU5H92DGF336SKED4V3FNKVJ8AS6";
export const MAX_COUNT_OF_ATTEMPTS_FOR_DATA_RETRIEVAL = 50;
export const MAX_ATTEMPTS_TO_RETRIEVE_TRANSACTIONS_DATA = 80;
export const LANDING_PATH = "/welcome";
export const RAMP_NETWORK_API_KEY = "38dzmcsoh4upgbjhvmjxh9egbh5678cxnxhc5whe";
export const RAMP_WEBHOOK_STATUS_URL = "https://pacific-sierra-54547.herokuapp.com/webhook";
export const RAMP_WIDGET_STAGING_URL = "https://ri-widget-staging.firebaseapp.com/";
export const PUBLIC_LOGO_LINK = "https://dev1.rabbit.io/logo.svg";
export const LOG_LEVEL = "trace"; // of "trace", "debug"
